<a href="https://colab.research.google.com/github/equester/TataTelecomAI/blob/master/TATA_CLassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np                                                 # Implemennts milti-dimensional array and matrices
import pandas as pd                                                # For data manipulation and analysis
import pandas_profiling
import matplotlib.pyplot as plt                                    # Plotting library for Python programming language and it's numerical mathematics extension NumPy
import seaborn as sns                                              # Provides a high level interface for drawing attractive and informative statistical graphics
%matplotlib inline
sns.set()

from subprocess import check_output

In [0]:
data = pd.read_csv("https://raw.githubusercontent.com/equester/TataTelecomAI/master/Sample%20Data/data_P.csv")

In [17]:
data.tail(5)

Incoming Attempts  Normal Term Seizures  Answered Calls  \
545               1203                   348             100   
546              11272                  8553             235   
547              53099                 44837           13750   
548               1325                  1112              30   
549              48929                 47024           25699   

     Normal Not Answer Calls  Outgoing Seizures  FEV Seizures  \
545                      248                360             1   
546                     8318               8576            22   
547                    31087              48122          1965   
548                     1082               1153            37   
549                    21325              47652           533   

     Network Conversation Minutes        NER       ACD New Pricing Service  
545                    222.316667  96.935933  2.223167           Corporate  
546                    661.883333  99.988310  2.816525         Call Center  
547                  37163.766670  97.140195  2.702819           Corporate  
548                     96.050000  99.641577  3.201667         Call Center  
549                  83347.633330  99.798383  3.243225           Corporate

In [0]:
feature_cols = ['Incoming Attempts',	'Normal Term Seizures'	,'Answered Calls','Normal Not Answer Calls',	'Outgoing Seizures',	'FEV Seizures',	'Network Conversation Minutes',	'NER', 'ACD']                # create a Python list of feature names
X = data[feature_cols] 

In [19]:
print(type(X))
print(X.shape)

<class 'pandas.core.frame.DataFrame'>
(550, 9)


In [20]:
X = data.loc[:,data.columns != 'New Pricing Service']
X.head()

Incoming Attempts  Normal Term Seizures  Answered Calls  \
0                 41                    41              40   
1                239                    49              11   
2               8019                   459             188   
3                 10                     8               8   
4                117                    96              13   

   Normal Not Answer Calls  Outgoing Seizures  FEV Seizures  \
0                        1                 41             0   
1                       38                 71            14   
2                      271                643           103   
3                        0                  8             0   
4                       83                112             4   

   Network Conversation Minutes         NER       ACD  
0                     14.533333  100.000000  0.363333  
1                     36.666667   85.964912  3.333333  
2                   1435.066667   85.000000  7.633333  
3                     13.133333  100.000000  1.641667  
4                     64.016667   88.888889  4.924359

In [0]:
y = data['New Pricing Service']

In [23]:
y.unique()

array(['Call Center', 'Corporate'], dtype=object)

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [25]:
print('Train cases as below')
print('X_train shape: ',X_train.shape)
print('y_train shape: ',y_train.shape)
print('\nTest cases as below')
print('X_test shape: ',X_test.shape)
print('y_test shape: ',y_test.shape)

Train cases as below
('X_train shape: ', (440, 9))
('y_train shape: ', (440,))

Test cases as below
('X_test shape: ', (110, 9))
('y_test shape: ', (110,))


In [26]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [0]:
from sklearn.tree import DecisionTreeClassifier
DTree = DecisionTreeClassifier()
DTree.fit(X_train,y_train)

In [0]:
y_pred_train = logreg.predict(X_train)

In [0]:
y_pred_test = logreg.predict(X_test)

In [29]:
print y_pred_train

['Corporate' 'Call Center' 'Corporate' 'Call Center' 'Corporate'
 'Call Center' 'Call Center' 'Call Center' 'Call Center' 'Corporate'
 'Call Center' 'Call Center' 'Call Center' 'Call Center' 'Call Center'
 'Call Center' 'Corporate' 'Corporate' 'Call Center' 'Call Center'
 'Corporate' 'Call Center' 'Call Center' 'Call Center' 'Corporate'
 'Corporate' 'Corporate' 'Call Center' 'Call Center' 'Call Center'
 'Call Center' 'Call Center' 'Corporate' 'Call Center' 'Call Center'
 'Call Center' 'Call Center' 'Call Center' 'Call Center' 'Call Center'
 'Call Center' 'Call Center' 'Call Center' 'Corporate' 'Call Center'
 'Call Center' 'Call Center' 'Call Center' 'Call Center' 'Corporate'
 'Corporate' 'Corporate' 'Corporate' 'Corporate' 'Call Center' 'Corporate'
 'Call Center' 'Corporate' 'Call Center' 'Call Center' 'Call Center'
 'Corporate' 'Call Center' 'Corporate' 'Call Center' 'Call Center'
 'Call Center' 'Call Center' 'Call Center' 'Corporate' 'Call Center'
 'Call Center' 'Call Center' 'Call C

In [30]:
logreg.predict_proba(X_test)

/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/base.py:297: RuntimeWarning: overflow encountered in exp
  np.exp(prob, prob)


array([[5.17676372e-001, 4.82323628e-001],
       [5.22471521e-001, 4.77528479e-001],
       [7.42369803e-001, 2.57630197e-001],
       [5.01095165e-001, 4.98904835e-001],
       [5.25750568e-001, 4.74249432e-001],
       [5.17802675e-001, 4.82197325e-001],
       [5.17862568e-001, 4.82137432e-001],
       [5.13088311e-001, 4.86911689e-001],
       [5.05555976e-001, 4.94444024e-001],
       [0.00000000e+000, 1.00000000e+000],
       [5.17059141e-001, 4.82940859e-001],
       [5.38889975e-001, 4.61110025e-001],
       [5.21187520e-001, 4.78812480e-001],
       [5.18346764e-001, 4.81653236e-001],
       [5.14014116e-001, 4.85985884e-001],
       [3.25574508e-001, 6.74425492e-001],
       [0.00000000e+000, 1.00000000e+000],
       [5.21817053e-001, 4.78182947e-001],
       [5.01149482e-001, 4.98850518e-001],
       [5.13077129e-001, 4.86922871e-001],
       [5.18529690e-001, 4.81470310e-001],
       [1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [1.0

In [31]:
from sklearn.metrics import accuracy_score
print('Accuracy score for test data is:', accuracy_score(y_test,y_pred_test))


('Accuracy score for test data is:', 0.7272727272727273)


In [32]:
from sklearn.metrics import confusion_matrix

confusion_matrix = pd.DataFrame(confusion_matrix(y_test, y_pred_test))

print(confusion_matrix)

    0   1
0  45   4
1  26  35


In [35]:
confusion_matrix.index = ['Call Center','Corporate']
confusion_matrix.columns = ['Call Center','Corporate']
print(confusion_matrix)

             Call Center  Corporate
Call Center           45          4
Corporate             26         35


In [42]:
X_test[:2]

Incoming Attempts  Normal Term Seizures  Answered Calls  \
160                240                   148              40   
306                224                   103              36   

     Normal Not Answer Calls  Outgoing Seizures  FEV Seizures  \
160                      108                180            23   
306                       67                110             7   

     Network Conversation Minutes         NER       ACD  
160                     99.950000   94.267516  2.498750  
306                      4.283333  100.000000  0.118981

In [41]:
logreg.predict(X_test[:2])

array(['Call Center', 'Call Center'], dtype=object)

In [43]:
logreg.intercept_

array([-6.43041059e-06])

array([[-1.04460608e-04,  3.61375876e-04,  1.64241286e-04,
         1.97134590e-04, -5.09361445e-04,  7.61944356e-04,
         1.56999795e-04, -7.28672776e-04,  6.26624876e-05]])

In [46]:
logreg.intercept_
logreg.coef_
feature_cols.insert(0,'Intercept')
coef = logreg.coef_.tolist()
coef.insert(0, logreg.intercept_)


('Intercept', array([-6.43041059e-06]))
('Intercept', [-0.00010446060831015337, 0.00036137587578189355, 0.0001642412857717886, 0.0001971345900107404, -0.0005093614451096853, 0.0007619443558759377, 0.00015699979485722548, -0.0007286727762346164, 6.266248761007911e-05])


In [47]:
eq1 = zip(feature_cols, coef)

for c1,c2 in eq1:
    print(c1,c2)

('Intercept', array([-6.43041059e-06]))
('Intercept', [-0.00010446060831015337, 0.00036137587578189355, 0.0001642412857717886, 0.0001971345900107404, -0.0005093614451096853, 0.0007619443558759377, 0.00015699979485722548, -0.0007286727762346164, 6.266248761007911e-05])


In [0]:
data['Predicted'] = logreg.predict(data.loc[:,data.columns != 'New Pricing Service'])

In [0]:
data.to_csv("predicted_Output.csv")